# Generated by Django 6.1.1 on 2026-10-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Details_DB',
            fields=[
                ('company', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=10)),
                ('reg_no', models.IntegerField()),
                ('myear', models.IntegerField()),
                ('onwer_name', models.CharField(max_length=20)),
                ('owner_address', models.TextField()),
                ('licence_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('num_plate', models.IntegerField()),
            ],
        ),
    ]
