# Generated by Django 6.1.1 on 2026-10-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_details_db',
            name='model',
            field=models.CharField(max_length=20),
        ),
    ]
